version: '2'

volumes:
  octostack-db-store:
    external: true


services:

#
#   Infrastructure services
#  

#############################################################################
# AMQP broker
#############################################################################
  amqpbroker:
    image: rabbitmq:management
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=openstack
      - RABBITMQ_DEFAULT_PASS=rabbitpass
#############################################################################
# SQL Database server
#############################################################################
  sqldatabase:
    image: mariadb:10.1
    environment:
      - MYSQL_ROOT_PASSWORD=mysqlpass
    command: --max-connections=2000 --silent
    volumes:
      - octostack-db-store:/var/lib/mysql
#############################################################################
# Keystone identity server
#   The "key.stone" additional network alias is due to that tacker's web UI
#   only accepts hostnames with a domain specifier (this is in turn is
#   due to the Django Python web framework used by Horizon)
#############################################################################
  keystone:
    networks: 
      default:
        aliases:
          - key.stone
    image: ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/keystone:${OCTOSTACK_VERSION}
    ports:
      - 5000:5000
      - 35357:35357


#
#   Controller services
#  


#############################################################################
# glance
#############################################################################
  glance:
    image: ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/glance:${OCTOSTACK_VERSION}
    ports:
      - 9292:9292
    privileged: true
    hostname: glance
#############################################################################
# cinder
#############################################################################
  cinder:
    image: ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/cinder:${OCTOSTACK_VERSION}
    hostname: cinder
#############################################################################
# nova
#############################################################################
  nova:
    image: ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/nova:${OCTOSTACK_VERSION}
    privileged: true
    ports:
      - 6080:6080
      - ${SPICE_HOST_PORT}:6082
      - 8774:8774
    hostname: nova
#############################################################################
# neutron
#############################################################################
  neutron:
    image: ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/neutron:${OCTOSTACK_VERSION}
    privileged: true
    hostname: neutron
    ports:
      - 9696:9696


#
#   Management services
#

#############################################################################
# heat
#############################################################################
  heat:
    image: ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/heat:${OCTOSTACK_VERSION}
    hostname: heat
#############################################################################
# tacker
#############################################################################
  tacker:
    image: ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/tacker:${OCTOSTACK_VERSION}
#############################################################################
# horizon
#############################################################################
  horizon:
    image: ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/horizon:${OCTOSTACK_VERSION}
    ports:
      - ${HORIZON_PORT}:80

#############################################################################
# cli : openstack Command Line Client
#############################################################################
  cli:
    image: ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}/util:${OCTOSTACK_VERSION}
    command: bash -c "sleep infinity"
    volumes:
      - ${PWD}:/work
#############################################################################
# procera_data_server : HTTP server used for providing operational artifacts,
#                       such as vm images and heat templates.
#############################################################################
  procera_data_server:
    image: busybox
    command: sh -c "httpd -f -h /data"
    volumes:
      -  ${DATA_DIRECTORY}:/data
#############################################################################


  compute-01:
    hostname: compute-node-01
    extends:
      file: ../shared/compute-base.yml
      service: compute


  compute-02:
    hostname: compute-node-02
    extends:
      file: ../shared/compute-base.yml
      service: compute
    command: compute-only

  compute-03:
    hostname: compute-node-03
    extends:
      file: ../shared/compute-base.yml
      service: compute
    command: compute-only

  storage:
    extends:
      file: ../shared/storage-base.yml
      service: storage

  glusterfs:
    extends:
      file: ../shared/storage-base.yml
      service: glusterfs


